[workspace]
members = [
    "contracts/escrow",
    "contracts/oracle",
    "contracts/contract-registry",
    "contracts/smile4money-common",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
soroban-sdk = { version = "22.0.11" }
smile4money-common = { path = "contracts/smile4money-common" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
